AcmeCorporation/Controllers/UserProfilesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AcmeCorporation.Areas.Identity.Data;
using AcmeCorporation.Data;
using Microsoft.AspNetCore.Authorization;
using AcmeCorporation.Core.ApplicationServices;
using X.PagedList;

namespace AcmeCorporation.Controllers
{
    public class UserProfilesController : Controller
    {
        private readonly DrawContext _context;
        private readonly IUserProfileService _userService;
        public UserProfilesController(DrawContext context, IUserProfileService userService)
        {
            _context = context;
            _userService = userService;
        }
        [Authorize]
        // GET: UserProfiles
        public async  Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            

            var userProf = from s in _context.UserProfile
                           .Include(ud => ud.UserInDraw)
                           select s;

            if (userProf == null)
            {
                return RedirectToAction(actionName: nameof(Index),
                     controllerName: "Home");
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                userProf = userProf.Where(s => s.LastName.Contains(searchString)
                                       || s.FirstName.Contains(searchString));
            }
            var pageNumber = page ?? 1;
            var pageSize = 10; //Show 10 rows every time
            var brands = await userProf.ToPagedListAsync(pageNumber, pageSize);
            return View(brands);
        }

        [Authorize]
        // GET: UserProfiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(actionName: nameof(Index),
                    controllerName: "Home");
            }
            var userProfile = await _context.UserProfile
                .Include(u => u.User)
                .Include(p => p.UserProducts)
                .ThenInclude(sn => sn.ProductSerialNumber)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userProfile == null)
            {
                return RedirectToAction(actionName: nameof(Index),
                    controllerName: "Home");
            }

            return View(userProfile);
        }

        
        [Authorize]
        public async Task<IActionResult> DrawForm(string SN, string Email)
        {
            if (!string.IsNullOrEmpty(SN) && !string.IsNullOrEmpty(Email))
            {
                var validation = await _userService.Draw(SN, Email);
                TempData["testmsg"] = validation;
                return RedirectToAction(nameof(Index));
            }
            else if (string.IsNullOrEmpty(SN) && !string.IsNullOrEmpty(Email))
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: UserProfiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfile = await _context.UserProfile.FindAsync(id);
            if (userProfile == null)
            {
                return NotFound();
            }
            return View(userProfile);
        }

        public IList<UserProfile> UserProds { get; set; }

        public async Task OnGetAsync()
        {
            UserProds = await _context.UserProfile
                .Include(c => c.UserProducts)
                .AsNoTracking()
                .ToListAsync();
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,BirthDate,UserInDrawId")] UserProfile userProfile)
        {
            if (id != userProfile.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userProfile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    //if (!UserProfileExists(userProfile.Id))
                    //{
                    //    return NotFound();
                    //}
                    //else
                    //{
                    //    throw;
                    //}
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfile = await _context.UserProfile
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userProfile == null)
            {
                return NotFound();
            }

            return View(userProfile);
        }

        // POST: UserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userProfile = await _context.UserProfile.FindAsync(id);
            _context.UserProfile.Remove(userProfile);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserProfileExists(int id)
        {
            return _context.UserProfile.Any(e => e.Id == id);
        }
    }
}

AcmeCorporation/Views/UserProfiles/Delete.cshtml
@model AcmeCorporation.Areas.Identity.Data.UserProfile

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AcmeCorporation/Views/UserProfiles/Details.cshtml
@model AcmeCorporation.Areas.Identity.Data.UserProfile

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>UserProfile</h4>
    <hr />


    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
    </dl>

    @foreach (var item in Model.UserProducts)
    {
        <div class="card-columns">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(model => item.ProductName)</h5>
                    <h6 class="card-subtitle mb-2 text-muted">
                        Product information:
                    </h6>
                    <p class="card-text">
                        <div>
                            @Html.DisplayNameFor(model => item.ProductSerialNumber.ValidForLottery)
                            @Html.DisplayFor(model => item.ProductSerialNumber.ValidForLottery)
                        </div>
                        <div>
                            @Html.DisplayNameFor(model => item.ProductSerialNumber.ProductSerialNumber)
                        </div>
                        <div>
                            @Html.DisplayFor(model => item.ProductSerialNumber.ProductSerialNumber)
                        </div>
                    </p>
                    <a asp-action="Edit" asp-route-id="@Model.Id">
                        Edit
                    </a>
                    <a asp-action="Index">
                        Back to List
                    </a>
                </div>
            </div>
        </div>
    }
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AcmeCorporation/Views/UserProfiles/DrawForm.cshtml
@model AcmeCorporation.Areas.Identity.Data.UserProfile



@{
    ViewData["Title"] = "DrawForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Draw Form</h1>

<h4>UserProfile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
        @using (Html.BeginForm("Login"))
        {
            <input class="form-control" type="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="Email" />
            <input class="form-control" type="text" name="SN" id="Sn" placeholder="Insert SerialNumber" />
            <input class="btn btn-primary" type="submit" value="Submit" />
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AcmeCorporation/Views/UserProfiles/Edit.cshtml
@model AcmeCorporation.Areas.Identity.Data.UserProfile

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>UserProfile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserInDrawId" class="control-label"></label>
                <select asp-for="UserInDrawId" class="form-control" asp-items="ViewBag.UserInDrawId"></select>
                <span asp-validation-for="UserInDrawId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AcmeCorporation/Views/UserProfiles/Index.cshtml
@using X.PagedList.Mvc.Core;

@model X.PagedList.IPagedList<AcmeCorporation.Areas.Identity.Data.UserProfile>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using Microsoft.AspNetCore.Identity
@using AcmeCorporation.Areas.Identity.Data
@inject SignInManager<User> SignInManager
@{
    ViewBag.Title = "UsersInDraw"; ;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
@if (TempData["testmsg"] != null)
{
    <script type="text/javascript">
       alert("@TempData["testmsg"]");
    </script>
}
@if (SignInManager.IsSignedIn(User))
{
        <p>
            @Html.ActionLink("Draw Form", "DrawForm")
        </p>

    @using (Html.BeginForm("Index", "UserProfiles", FormMethod.Get))
    {
        <p>
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().UserInDraw.HasEnteredAmount)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserInDraw.HasEnteredAmount)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))